import React from 'react';
import SectionCard from './SectionCard';

/**
 * AI Operator Brief Capability Shell (S10 Layout Shell).
 * Displays the 6-question structured briefing generated by the backend.
 */
export default function OperatorBriefShell({ brief }) {
  const getSeverityBadge = () => {
    switch (brief?.severity) {
      case 'CRITICAL':
        return { text: 'CRITICAL', variant: 'critical' };
      case 'WARNING':
        return { text: 'WARNING', variant: 'warning' };
      case 'INFO':
        return { text: 'INFO', variant: 'accent' };
      case 'NOMINAL':
      default:
        return { text: 'NOMINAL', variant: 'nominal' };
    }
  };

  const badge = getSeverityBadge();

  return (
    <SectionCard
      title="AI Operator Brief"
      subtitle={`Operational decision-support summary (${brief?.generated_by || 'template-fallback'})`}
      badge={badge.text}
      badgeVariant={badge.variant}
      className="operator-brief-card"
    >
      <div className="brief-grid">
        <div className="brief-section-item highlight">
          <span className="brief-item-label">1. Current Situation</span>
          <p className="brief-item-text">{brief?.situation || 'Awaiting brief synthesis...'}</p>
        </div>

        <div className="brief-section-item">
          <span className="brief-item-label">2. Likely Cause</span>
          <p className="brief-item-text">{brief?.likely_cause || 'Awaiting brief synthesis...'}</p>
        </div>

        <div className="brief-section-item alert-box">
          <span className="brief-item-label">3. Main Risk</span>
          <p className="brief-item-text">{brief?.main_risk || 'Awaiting brief synthesis...'}</p>
        </div>

        <div className="brief-section-item action-box">
          <span className="brief-item-label">4. Recommended Action</span>
          <p className="brief-item-text font-semibold">{brief?.recommended_action || 'Awaiting brief synthesis...'}</p>
        </div>

        <div className="brief-section-item">
          <span className="brief-item-label">5. Action Rationale</span>
          <p className="brief-item-text">{brief?.rationale || 'Awaiting brief synthesis...'}</p>
        </div>

        <div className="brief-section-item warning-box">
          <span className="brief-item-label">6. Consequence If Ignored</span>
          <p className="brief-item-text">{brief?.consequence_if_ignored || 'Awaiting brief synthesis...'}</p>
        </div>
      </div>

      <div className="shell-placeholder compact">
        <span className="shell-tag">Active Endpoint: GET /api/operator-brief • Non-Autonomous Decision Support</span>
      </div>
    </SectionCard>
  );
}
